# action.yml
name: 'Slack Workflow Norify'
description: 'Send slack notification for CI workflow status.'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  workflow_name:  # id of input
    description: 'name of current workflow'
    required: true
    default: '<placeholder>'  
  workflow_run_number:  # id of input
    description: 'A unique number for each workflow run within a repository.'
    required: true
    default: '<placeholder>'   
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
    - ${{ inputs.workflow_name }}
    - ${{ inputs.workflow_run_number }}
